import {
  createFeeEarner,
  createFirm,
  registerInboundEmailKey,
  sha256Hex,
} from '@meetlou/records/admin';
import { createMatter, createParticipant } from '@meetlou/records';
import type { RecordError } from '@meetlou/records';
import { firmRow, matterRow, participantRow } from '@meetlou/domain';
import type { FirmRow, MatterRow, ParticipantRow, Result } from '@meetlou/domain';
import { z } from 'zod';
import { serviceClient, signedInClient } from './clients';
import { assertLocal, localEnv } from './local-env';
import type { LocalEnv } from './local-env';

/**
 * The matter every later test uses. Safe to run repeatedly: it finds before it creates, so a
 * second run returns the same records (and the same inbound_slug) instead of adding more.
 *
 * inbound_slug is generated by the database from the address plus 96 random bits, so it is
 * different on every fresh database. Read it from the result; do not hard-code it.
 */
export const ARMSTRONG = {
  firm: { name: 'Armstrong & Co', mailDomain: 'matters.armstrongco.co.uk' },
  feeEarner: {
    email: 'fee.earner@example.org',
    password: process.env['SEED_FEE_EARNER_PASSWORD'] ?? 'local-dev-only-fee-earner',
    // Ofcom drama-range mobile. This is the number the voice webhook dials.
    phoneE164: '+447700900123',
  },
  matter: {
    reference: 'MTR-1001',
    propertyAddress: '14 Meadow Road, Sale M33 2QX',
    kind: 'purchase',
    // Ofcom drama-range Manchester number. Calls to it route to this matter.
    lineE164: '+442079460958',
  },
  // The Inbound Parse URL credential for local use: 256 bits, made up, committed on purpose. Real
  // secrets are generated by createInboundEmailKey and never appear in the repo.
  inboundEmailSecret: 'b7e2d4f1a9c3058e6d1b4a7f2c9e0d3815a6b4c7e9f20134d5a8b6c7e1f0a923',
  participants: [
    {
      displayName: 'Sarah Whitfield',
      access: 'client',
      role: 'client',
      phoneE164: '+447700900301',
      email: 'sarah.whitfield@example.org',
    },
    // Chain only: sees chain events, never documents.
    {
      displayName: 'Priya Nandra',
      access: 'chain',
      role: 'estate_agent',
      phoneE164: '+447700900302',
      email: 'priya.nandra@example.org',
    },
  ],
} as const;

export interface SeedResult {
  firm: FirmRow;
  feeEarner: {
    memberId: string;
    userId: string;
    email: string;
    password: string;
    phoneE164: string;
  };
  matter: MatterRow;
  inboundAddress: string;
  /** The Inbound Parse URL credential: path = /<keyId>/<secret>. */
  inboundEmail: { keyId: string; secret: string; urlPath: string };
  sarahWhitfield: ParticipantRow;
  priyaNandra: ParticipantRow;
}

function unwrap<T>(what: string, result: Result<T, RecordError>): T {
  if (!result.ok) throw new Error(`${what}: ${result.error.code}: ${result.error.message}`);
  return result.value;
}

export async function seedArmstrong(env: LocalEnv = localEnv()): Promise<SeedResult> {
  assertLocal(env);
  const admin = serviceClient(env);

  // Firm
  const existingFirm = await admin
    .from('firms')
    .select('id, name, mail_domain')
    .eq('mail_domain', ARMSTRONG.firm.mailDomain)
    .maybeSingle();
  if (existingFirm.error !== null) throw new Error(existingFirm.error.message);
  const firm: FirmRow =
    existingFirm.data === null
      ? unwrap('createFirm', await createFirm(admin, ARMSTRONG.firm))
      : firmRow.parse(existingFirm.data);

  // Fee earner (a login attached to the firm). Found by their login, not "any member of the
  // firm": other tests add members to this firm.
  const logins = await admin.auth.admin.listUsers({ perPage: 1000 });
  if (logins.error !== null) throw new Error(logins.error.message);
  const login = logins.data.users.find((u) => u.email === ARMSTRONG.feeEarner.email);
  const members =
    login === undefined
      ? undefined
      : await admin
          .from('firm_users')
          .select('id, user_id')
          .eq('firm_id', firm.id)
          .eq('user_id', login.id)
          .maybeSingle();
  if (members?.error !== null && members?.error !== undefined)
    throw new Error(members.error.message);
  const member = members?.data ?? undefined;
  const feeEarner =
    member === undefined
      ? unwrap(
          'createFeeEarner',
          await createFeeEarner(admin, { firmId: firm.id, ...ARMSTRONG.feeEarner }),
        )
      : z
          .object({ id: z.uuid(), user_id: z.uuid() })
          .transform((row) => ({ memberId: row.id, userId: row.user_id }))
          .parse(member);
  const { memberId, userId } = feeEarner;

  // From here on, act as the fee earner: matter and participants are created through RLS.
  const asFeeEarner = await signedInClient(
    env,
    ARMSTRONG.feeEarner.email,
    ARMSTRONG.feeEarner.password,
  );

  const found = await asFeeEarner
    .from('matters')
    .select(
      'id, firm_id, reference, kind, property_address, inbound_slug, line_e164, responsible_fee_earner_id',
    )
    .eq('firm_id', firm.id)
    .eq('reference', ARMSTRONG.matter.reference)
    .maybeSingle();
  if (found.error !== null) throw new Error(found.error.message);
  const matter: MatterRow =
    found.data === null
      ? unwrap(
          'createMatter',
          await createMatter(asFeeEarner, {
            firmId: firm.id,
            ...ARMSTRONG.matter,
            responsibleFeeEarnerId: memberId,
          }),
        ).matter
      : matterRow.parse(found.data);

  const existing = await asFeeEarner
    .from('participants')
    .select('id, firm_id, matter_id, user_id, access, role, display_name')
    .eq('matter_id', matter.id);
  if (existing.error !== null) throw new Error(existing.error.message);
  const have = existing.data.map((row) => participantRow.parse(row));

  const participants: ParticipantRow[] = [];
  for (const spec of ARMSTRONG.participants) {
    const already = have.find((p) => p.display_name === spec.displayName);
    participants.push(
      already ??
        unwrap(
          `createParticipant(${spec.displayName})`,
          await createParticipant(asFeeEarner, { firmId: firm.id, matterId: matter.id, ...spec }),
        ),
    );
  }
  const [sarahWhitfield, priyaNandra] = participants;
  if (sarahWhitfield === undefined || priyaNandra === undefined)
    throw new Error('participants missing');

  // The Inbound Parse URL credential: find the local key or register it.
  const secretHash = await sha256Hex(ARMSTRONG.inboundEmailSecret);
  const keys = await admin
    .from('inbound_email_keys')
    .select('id')
    .eq('firm_id', firm.id)
    .eq('secret_sha256', secretHash)
    .is('revoked_at', null)
    .limit(1);
  if (keys.error !== null) throw new Error(keys.error.message);
  const existingKey = keys.data[0];
  const inboundEmail =
    existingKey === undefined
      ? unwrap(
          'registerInboundEmailKey',
          await registerInboundEmailKey(admin, firm.id, ARMSTRONG.inboundEmailSecret),
        )
      : {
          keyId: z.object({ id: z.uuid() }).parse(existingKey).id,
          secret: ARMSTRONG.inboundEmailSecret,
          urlPath: `/${z.object({ id: z.uuid() }).parse(existingKey).id}/${ARMSTRONG.inboundEmailSecret}`,
        };

  return {
    firm,
    feeEarner: { memberId, userId, ...ARMSTRONG.feeEarner },
    matter,
    inboundAddress: `${matter.inbound_slug}@${ARMSTRONG.firm.mailDomain}`,
    inboundEmail,
    sarahWhitfield,
    priyaNandra,
  };
}

/** The values SendGrid fixtures need from the seed: the matter's address and the URL credential. */
export function seedVars(seed: SeedResult): Record<string, string> {
  return {
    slug: seed.matter.inbound_slug,
    mailDomain: seed.firm.mail_domain ?? '',
    inboundKeyId: seed.inboundEmail.keyId,
    inboundSecret: seed.inboundEmail.secret,
  };
}
