-- 0003 matters and participants.

create table public.matters (
  id               uuid primary key default gen_random_uuid(),
  firm_id          uuid not null references public.firms (id),
  reference        text not null check (length(btrim(reference)) > 0),
  kind             text not null check (kind in
                     ('sale', 'purchase', 'sale_and_purchase', 'remortgage', 'transfer_of_equity')),
  property_address text not null,
  -- The whole email routing mechanism: <readable-prefix>-<96 random bits as hex>@inbound domain.
  -- Always generated by the trigger below; a caller cannot choose (or weaken) it.
  inbound_slug     text not null unique
                     check (inbound_slug ~ '^[a-z0-9]+(-[a-z0-9]+)*-[0-9a-f]{24}$'),
  -- Routes inbound calls to this matter.
  line_e164        text unique check (line_e164 ~ '^\+[1-9][0-9]{6,14}$'),
  opened_at        timestamptz not null default now(),
  closed_at        timestamptz,
  created_at       timestamptz not null default now(),
  unique (firm_id, reference),
  -- Lets child tables prove that firm_id and matter_id agree.
  unique (id, firm_id)
);

create function app.make_inbound_slug(p_reference text) returns text
language sql volatile set search_path = ''
as $$
  select coalesce(
           nullif(btrim(left(btrim(regexp_replace(lower(p_reference), '[^a-z0-9]+', '-', 'g'), '-'), 30), '-'), ''),
           'matter'
         )
         || '-' || encode(extensions.gen_random_bytes(12), 'hex');
$$;

-- SECURITY DEFINER: browser roles have no EXECUTE on the slug generator, and must not.
create function app.matters_before_write() returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.inbound_slug := app.make_inbound_slug(new.reference);
  else
    if new.id is distinct from old.id
       or new.firm_id is distinct from old.firm_id
       or new.inbound_slug is distinct from old.inbound_slug then
      raise exception 'matters.id, firm_id and inbound_slug are immutable'
        using errcode = 'restrict_violation';
    end if;
  end if;
  return new;
end;
$$;
create trigger matters_before_write before insert or update on public.matters
  for each row execute function app.matters_before_write();

create table public.participants (
  id           uuid primary key default gen_random_uuid(),
  firm_id      uuid not null,
  matter_id    uuid not null,
  -- Set once the participant has a login. Null until then.
  user_id      uuid references auth.users (id),
  -- What they may see: 'client' (the client), 'chain' (everyone else in the chain).
  access       text not null check (access in ('client', 'chain')),
  role         text not null check (role in ('client', 'other_side_client', 'other_side_representative',
                 'estate_agent', 'lender', 'mortgage_broker', 'other')),
  display_name text not null,
  phone_e164   text check (phone_e164 ~ '^\+[1-9][0-9]{6,14}$'),
  email        text,
  created_at   timestamptz not null default now(),
  foreign key (matter_id, firm_id) references public.matters (id, firm_id),
  unique (matter_id, user_id)
);
create index participants_user_id_idx on public.participants (user_id) where user_id is not null;
create index participants_matter_id_idx on public.participants (matter_id);

-- The caller's access level on a matter ('client' | 'chain' | null).
create function app.participant_access(p_matter_id uuid) returns text
language sql stable security definer set search_path = ''
as $$
  select p.access from public.participants p
  where p.matter_id = p_matter_id and p.user_id = auth.uid();
$$;
revoke all on function app.participant_access(uuid) from public;
grant execute on function app.participant_access(uuid) to authenticated, service_role;

alter table public.matters enable row level security;
alter table public.matters force row level security;
alter table public.participants enable row level security;
alter table public.participants force row level security;

-- The firm sees every matter of its own. A participant sees no matter row at all: they
-- reach their matter only through the events and documents shared with them.
create policy matters_select_firm on public.matters
  for select to authenticated using (app.is_firm_user(firm_id));
create policy matters_insert_firm on public.matters
  for insert to authenticated
  with check (app.has_firm_role(firm_id, array['fee_earner', 'colp', 'admin']));
create policy matters_update_firm on public.matters
  for update to authenticated
  using (app.has_firm_role(firm_id, array['fee_earner', 'colp', 'admin']))
  with check (app.has_firm_role(firm_id, array['fee_earner', 'colp', 'admin']));

-- The firm sees all participants on its matters; a participant sees only their own row.
create policy participants_select_firm_or_self on public.participants
  for select to authenticated
  using (app.is_firm_user(firm_id) or user_id = auth.uid());
create policy participants_insert_firm on public.participants
  for insert to authenticated
  with check (app.has_firm_role(firm_id, array['fee_earner', 'colp', 'admin']));
create policy participants_update_firm on public.participants
  for update to authenticated
  using (app.has_firm_role(firm_id, array['fee_earner', 'colp', 'admin']))
  with check (app.has_firm_role(firm_id, array['fee_earner', 'colp', 'admin']));

-- Column-level grants: browser roles can never write inbound_slug or move a row between firms.
grant select on public.matters, public.participants to authenticated;
grant insert (firm_id, reference, kind, property_address, line_e164) on public.matters to authenticated;
grant update (reference, kind, property_address, line_e164, closed_at) on public.matters to authenticated;
grant insert (firm_id, matter_id, user_id, access, role, display_name, phone_e164, email)
  on public.participants to authenticated;
grant update (user_id, access, role, display_name, phone_e164, email) on public.participants to authenticated;

grant select, insert, update on public.matters, public.participants to service_role;
