-- 0013 inbound email: the URL credential, email ingest in one transaction, and threading.

-- ---- the credential in the Inbound Parse URL -----------------------------------------------
-- SendGrid Inbound Parse sends no signature, so the URL is the only protection:
--   https://<project>/functions/v1/sendgrid-inbound/<inbound_email_keys.id>/<secret>
-- The secret is 256 random bits generated by the application and shown once. Only its SHA-256
-- is stored, so a database read does not reveal it. Each firm has its own key(s) (one per
-- Inbound Parse hostname), so a leak reaches one firm; two live keys allow rotation without a gap.
create table public.inbound_email_keys (
  id            uuid primary key default gen_random_uuid(),
  firm_id       uuid not null references public.firms (id),
  secret_sha256 text not null check (secret_sha256 ~ '^[0-9a-f]{64}$'),
  created_at    timestamptz not null default now(),
  revoked_at    timestamptz
);
create index inbound_email_keys_firm_id_idx on public.inbound_email_keys (firm_id);

alter table public.inbound_email_keys enable row level security;
alter table public.inbound_email_keys force row level security;

-- The COLP and admins see that keys exist and whether they are revoked. The hash column is
-- not granted to them, so they cannot read it.
create policy inbound_email_keys_select_colp_admin on public.inbound_email_keys
  for select to authenticated
  using (app.has_firm_role(firm_id, array['colp', 'admin']));

grant select (id, firm_id, created_at, revoked_at) on public.inbound_email_keys to authenticated;
grant select, insert, update on public.inbound_email_keys to service_role;

create trigger inbound_email_keys_audit after insert or update or delete on public.inbound_email_keys
  for each row execute function app.audit_change();

-- The application generates the secret and passes only its hash.
create function public.register_inbound_email_key(p_firm_id uuid, p_secret_sha256 text)
returns uuid
language sql security definer set search_path = ''
as $$
  insert into public.inbound_email_keys (firm_id, secret_sha256)
  values (p_firm_id, p_secret_sha256)
  returning id;
$$;
revoke all on function public.register_inbound_email_key(uuid, text) from public;
grant execute on function public.register_inbound_email_key(uuid, text) to service_role;

-- ---- columns the email pipeline needs --------------------------------------------------------
-- A message with no usable Message-ID is given sha256(raw)@meetlou.invalid so the idempotency
-- key still holds, and is flagged so nobody mistakes it for the sender's own.
alter table public.emails add column message_id_synthesised boolean not null default false;

-- What the bytes look like, beside what the sender claimed. Hostile senders choose the claim.
alter table public.attachments
  add column sniffed_content_type text not null default 'application/octet-stream';

-- ---- audit rows about email that is not filed ------------------------------------------------
alter table public.audit_log drop constraint audit_log_detail_check;
alter table public.audit_log add constraint audit_log_detail_check
  check (detail - array['changed_columns', 'counts', 'call_sid', 'to_e164', 'reason',
                        'recording_sid', 'email_sha256', 'recipient_domain'] = '{}'::jsonb);

-- One audit row per distinct message and kind of problem, however often SendGrid redelivers.
create unique index audit_log_email_issue_key
  on public.audit_log ((detail ->> 'email_sha256'), action)
  where action like 'email.%' and detail ? 'email_sha256';

-- The recipient's local part is deliberately NOT recorded: a mistyped address can be one
-- character from a real matter's address, and an address that belongs to another firm must
-- not leak into this firm's audit log. The domain, the reason and the message's hash identify it.
create function public.record_email_issue(
  p_action text, p_firm_id uuid, p_email_sha256 text, p_recipient_domain text, p_reason text
) returns void
language plpgsql security definer set search_path = ''
as $$
begin
  if p_action not in ('email.unrouted', 'email.rejected', 'email.duplicate_mismatch') then
    raise exception 'unknown email issue %', p_action;
  end if;
  insert into public.audit_log (firm_id, action, object_kind, detail)
  values (p_firm_id, p_action, 'email',
          jsonb_strip_nulls(jsonb_build_object('email_sha256', p_email_sha256,
                                               'recipient_domain', p_recipient_domain,
                                               'reason', p_reason)))
  on conflict ((detail ->> 'email_sha256'), action)
    where action like 'email.%' and detail ? 'email_sha256' do nothing;
end;
$$;
revoke all on function public.record_email_issue(text, uuid, text, text, text) from public;
grant execute on function public.record_email_issue(text, uuid, text, text, text) to service_role;

-- ---- ingest: the email, its attachments and their events, atomically and idempotently --------
create function public.ingest_email(
  p_matter_id uuid,
  p_message_id text,
  p_message_id_synthesised boolean,
  p_in_reply_to text,
  p_references text[],
  p_from_address text,
  p_to_addresses text[],
  p_cc_addresses text[],
  p_subject text,
  p_sent_at timestamptz,
  p_raw_storage_path text,
  p_raw_sha256 text,
  p_body_text_storage_path text,
  p_body_html_storage_path text,
  p_spf_result text,
  p_dkim_result text,
  p_attachments jsonb
) returns table (email_id uuid, created boolean)
language plpgsql security definer set search_path = ''
as $$
declare
  v_matter public.matters%rowtype;
  v_id uuid;
  v_existing_sha text;
  a jsonb;
  v_att_id uuid;
begin
  select * into v_matter from public.matters where id = p_matter_id;
  if not found then
    raise exception 'unknown matter' using errcode = 'foreign_key_violation';
  end if;

  insert into public.emails
    (firm_id, matter_id, message_id, message_id_synthesised, in_reply_to, references_ids,
     from_address, to_addresses, cc_addresses, subject, sent_at, raw_storage_path, raw_sha256,
     body_text_storage_path, body_html_storage_path, spf_result, dkim_result)
  values
    (v_matter.firm_id, p_matter_id, p_message_id, p_message_id_synthesised, p_in_reply_to,
     coalesce(p_references, '{}'), p_from_address, coalesce(p_to_addresses, '{}'),
     coalesce(p_cc_addresses, '{}'), p_subject, p_sent_at, p_raw_storage_path, p_raw_sha256,
     p_body_text_storage_path, p_body_html_storage_path, p_spf_result, p_dkim_result)
  on conflict (matter_id, message_id) do nothing
  returning id into v_id;

  if v_id is null then
    -- A redelivery of a message we hold. Nothing is written twice. If the bytes differ from
    -- what we hold under that Message-ID, that is worth a human's attention: the first one stands.
    select e.id, e.raw_sha256 into v_id, v_existing_sha
      from public.emails e where e.matter_id = p_matter_id and e.message_id = p_message_id;
    if v_existing_sha is distinct from p_raw_sha256 then
      perform public.record_email_issue('email.duplicate_mismatch', v_matter.firm_id, p_raw_sha256,
                                        null, 'same_message_id_different_bytes');
    end if;
    return query select v_id, false;
    return;
  end if;

  insert into public.events
    (firm_id, matter_id, kind, visibility, subject_kind, subject_id, occurred_at, actor_kind, summary)
  values
    (v_matter.firm_id, p_matter_id, 'email.received', 'firm', 'email', v_id, now(), 'system',
     'email received');

  for a in select * from jsonb_array_elements(coalesce(p_attachments, '[]'::jsonb)) loop
    insert into public.attachments
      (firm_id, matter_id, email_id, ordinal, filename, content_type, sniffed_content_type,
       byte_length, sha256, storage_path)
    values
      (v_matter.firm_id, p_matter_id, v_id, (a ->> 'ordinal')::int, a ->> 'filename',
       a ->> 'content_type', a ->> 'sniffed_content_type', (a ->> 'byte_length')::bigint,
       a ->> 'sha256', a ->> 'storage_path')
    returning id into v_att_id;

    insert into public.events
      (firm_id, matter_id, kind, visibility, subject_kind, subject_id, occurred_at, actor_kind, summary)
    values
      (v_matter.firm_id, p_matter_id, 'email.attachment_stored', 'firm', 'attachment', v_att_id,
       now(), 'system', 'attachment stored');
  end loop;

  return query select v_id, true;
end;
$$;
revoke all on function public.ingest_email(uuid, text, boolean, text, text[], text, text[], text[], text,
  timestamptz, text, text, text, text, text, text, jsonb) from public;
grant execute on function public.ingest_email(uuid, text, boolean, text, text[], text, text[], text[], text,
  timestamptz, text, text, text, text, text, text, jsonb) to service_role;

-- ---- threading: Message-ID, In-Reply-To and References. Never the subject. ---------------------
-- A view, not a stored column, so a parent that arrives after its reply never needs an update.
-- For each email: walk up through In-Reply-To (else the last References entry) while the parent
-- is on file for the same matter; the thread is named by the root reached, which for a chain
-- with gaps is the oldest reference we can see (References[1], else In-Reply-To, else itself).
create view public.email_threads with (security_invoker = true) as
with recursive node as (
  select e.id, e.matter_id, e.message_id,
         coalesce(e.references_ids[1], e.in_reply_to, e.message_id) as fallback_key,
         coalesce(e.in_reply_to, e.references_ids[cardinality(e.references_ids)]) as parent_message_id
    from public.emails e
), walk as (
  select n.id as email_id, n.matter_id, n.fallback_key as thread_key, n.parent_message_id, 0 as depth
    from node n
  union all
  select w.email_id, w.matter_id, p.fallback_key, p.parent_message_id, w.depth + 1
    from walk w
    join node p on p.matter_id = w.matter_id and p.message_id = w.parent_message_id
   where w.depth < 50 -- a malicious loop of references stops here
)
select distinct on (w.email_id)
       w.email_id, w.matter_id, w.thread_key
  from walk w
 order by w.email_id, w.depth desc;
grant select on public.email_threads to authenticated, service_role;
